import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Professional PDF Generator for HU-VMS Reports
class PDFGenerator {
    constructor() {
        this.primaryColor = [74, 144, 226]; // #4a90e2
        this.secondaryColor = [53, 122, 189]; // #357abd
        this.darkColor = [30, 60, 114]; // #1e3c72
        this.textColor = [51, 51, 51];
        this.lightGray = [240, 240, 240];
    }

    // Add professional header with logo and title
    addHeader(doc, title, subtitle = '') {
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header background
        doc.setFillColor(...this.primaryColor);
        doc.rect(0, 0, pageWidth, 40, 'F');

        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text('HU-VMS', 20, 18);

        doc.setFontSize(14);
        doc.text(title, 20, 28);

        if (subtitle) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text(subtitle, 20, 35);
        }

        // Date on right
        doc.setFontSize(9);
        const dateStr = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
        doc.text(dateStr, pageWidth - 20, 18, { align: 'right' });
        doc.text(new Date().toLocaleTimeString('en-US'), pageWidth - 20, 25, { align: 'right' });
    }

    // Add professional footer
    addFooter(doc, pageNumber, totalPages) {
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        doc.setDrawColor(...this.primaryColor);
        doc.setLineWidth(0.5);
        doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);

        doc.setTextColor(...this.textColor);
        doc.setFontSize(8);
        doc.text('Haramaya University - Vehicle Management System', 20, pageHeight - 12);
        doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
        doc.text('Generated by HU-VMS Driver Portal', pageWidth / 2, pageHeight - 12, { align: 'center' });
    }

    // Add recipient information
    addRecipient(doc, recipient, yPos = 50) {
        doc.setFillColor(...this.lightGray);
        doc.roundedRect(20, yPos, 170, 25, 3, 3, 'F');

        doc.setTextColor(...this.darkColor);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('TO:', 25, yPos + 8);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.text(recipient.name, 25, yPos + 15);
        doc.setFontSize(9);
        doc.text(recipient.department, 25, yPos + 21);
    }

    // Generate Fuel Report PDF
    generateFuelReport(data, recipient = 'Admin') {
        const doc = new jsPDF();

        this.addHeader(doc, 'Fuel Report', 'Driver Fuel Management');

        // Recipient
        const recipientInfo = {
            name: recipient === 'Admin' ? 'Administration Office' : 'Transport Office',
            department: recipient === 'Admin' ? 'University Administration' : 'Transport Management Department'
        };
        this.addRecipient(doc, recipientInfo, 50);

        // Report Details
        doc.setTextColor(...this.darkColor);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Report Details', 20, 90);

        // Report Type Badge
        const reportType = data.reportType === 'refill' ? 'FUEL REFILL' : 'FUEL CONSUMPTION';
        doc.setFillColor(...this.primaryColor);
        doc.roundedRect(20, 95, 50, 10, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(reportType, 45, 101.5, { align: 'center' });

        // Details Table
        const tableData = [
            ['Date', data.date || new Date().toLocaleDateString()],
            ['Amount', `${data.amount} Liters`],
            ['Odometer Reading', `${data.odometer} km`]
        ];

        if (data.reportType === 'refill') {
            tableData.push(['Cost', `${data.cost} ETB`]);
            if (data.station) {
                tableData.push(['Gas Station', data.station]);
            }
        }

        tableData.push(['Driver Name', data.driverName || 'John Doe']);
        tableData.push(['Vehicle ID', data.vehicleId || 'VEH-001']);
        tableData.push(['License Plate', data.licensePlate || 'ABC-1234']);

        doc.autoTable({
            startY: 110,
            head: [],
            body: tableData,
            theme: 'striped',
            headStyles: {
                fillColor: this.primaryColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold'
            },
            styles: {
                fontSize: 10,
                cellPadding: 5
            },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 60 },
                1: { cellWidth: 110 }
            },
            margin: { left: 20, right: 20 }
        });

        // Notes section
        if (data.notes) {
            const finalY = doc.lastAutoTable.finalY + 15;
            doc.setTextColor(...this.darkColor);
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Additional Notes:', 20, finalY);

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(...this.textColor);
            const splitNotes = doc.splitTextToSize(data.notes, 170);
            doc.text(splitNotes, 20, finalY + 7);
        }

        // Signature section
        const pageHeight = doc.internal.pageSize.getHeight();
        const signatureY = pageHeight - 60;

        doc.setDrawColor(...this.primaryColor);
        doc.line(20, signatureY, 90, signatureY);
        doc.setTextColor(...this.textColor);
        doc.setFontSize(9);
        doc.text('Driver Signature', 20, signatureY + 5);
        doc.setFontSize(8);
        doc.text(new Date().toLocaleString(), 20, signatureY + 10);

        this.addFooter(doc, 1, 1);

        // Save PDF
        const fileName = `Fuel_Report_${data.reportType}_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);

        return fileName;
    }

    // Generate Vehicle Issue Report PDF
    generateVehicleIssueReport(data, recipient = 'Admin') {
        const doc = new jsPDF();

        this.addHeader(doc, 'Vehicle Issue Report', 'Maintenance & Issue Reporting');

        const recipientInfo = {
            name: recipient === 'Admin' ? 'Administration Office' : 'Transport Office',
            department: recipient === 'Admin' ? 'University Administration' : 'Transport Management Department'
        };
        this.addRecipient(doc, recipientInfo, 50);

        // Issue Priority Badge
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Issue Report', 20, 90);

        const priorityColors = {
            low: [76, 175, 80],
            medium: [255, 152, 0],
            high: [244, 67, 54]
        };
        const priority = data.priority || 'medium';
        doc.setFillColor(...priorityColors[priority]);
        doc.roundedRect(20, 95, 45, 10, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.text(priority.toUpperCase() + ' PRIORITY', 42.5, 101.5, { align: 'center' });

        // Issue Details
        const tableData = [
            ['Report Date', data.date || new Date().toLocaleDateString()],
            ['Issue Type', data.issueType || 'Mechanical'],
            ['Priority Level', priority.toUpperCase()],
            ['Vehicle ID', data.vehicleId || 'VEH-001'],
            ['License Plate', data.licensePlate || 'ABC-1234'],
            ['Current Odometer', `${data.odometer || 'N/A'} km`],
            ['Driver Name', data.driverName || 'John Doe']
        ];

        doc.autoTable({
            startY: 110,
            body: tableData,
            theme: 'striped',
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 60 },
                1: { cellWidth: 110 }
            },
            margin: { left: 20, right: 20 }
        });

        // Issue Description
        const descY = doc.lastAutoTable.finalY + 15;
        doc.setTextColor(...this.darkColor);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('Issue Description:', 20, descY);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...this.textColor);
        const splitDesc = doc.splitTextToSize(data.description || 'No description provided', 170);
        doc.text(splitDesc, 20, descY + 7);

        // Signature
        const pageHeight = doc.internal.pageSize.getHeight();
        const signatureY = pageHeight - 60;

        doc.setDrawColor(...this.primaryColor);
        doc.line(20, signatureY, 90, signatureY);
        doc.setTextColor(...this.textColor);
        doc.setFontSize(9);
        doc.text('Driver Signature', 20, signatureY + 5);
        doc.setFontSize(8);
        doc.text(new Date().toLocaleString(), 20, signatureY + 10);

        this.addFooter(doc, 1, 1);

        const fileName = `Vehicle_Issue_Report_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);

        return fileName;
    }

    // Generate Complaint Report PDF
    generateComplaintReport(data, recipient = 'Admin') {
        const doc = new jsPDF();

        this.addHeader(doc, 'Complaint Report', 'Driver Complaint Submission');

        const recipientInfo = {
            name: recipient === 'Admin' ? 'Administration Office' : 'Transport Office',
            department: recipient === 'Admin' ? 'University Administration' : 'Transport Management Department'
        };
        this.addRecipient(doc, recipientInfo, 50);

        doc.setTextColor(...this.darkColor);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Complaint Details', 20, 90);

        const tableData = [
            ['Submission Date', data.date || new Date().toLocaleDateString()],
            ['Complaint Type', data.type || 'General'],
            ['Driver Name', data.driverName || 'John Doe'],
            ['Vehicle ID', data.vehicleId || 'VEH-001'],
            ['Contact', data.contact || 'N/A']
        ];

        doc.autoTable({
            startY: 95,
            body: tableData,
            theme: 'striped',
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 60 },
                1: { cellWidth: 110 }
            },
            margin: { left: 20, right: 20 }
        });

        const descY = doc.lastAutoTable.finalY + 15;
        doc.setTextColor(...this.darkColor);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('Complaint Description:', 20, descY);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...this.textColor);
        const splitDesc = doc.splitTextToSize(data.description || 'No description provided', 170);
        doc.text(splitDesc, 20, descY + 7);

        const pageHeight = doc.internal.pageSize.getHeight();
        const signatureY = pageHeight - 60;

        doc.setDrawColor(...this.primaryColor);
        doc.line(20, signatureY, 90, signatureY);
        doc.setTextColor(...this.textColor);
        doc.setFontSize(9);
        doc.text('Driver Signature', 20, signatureY + 5);
        doc.setFontSize(8);
        doc.text(new Date().toLocaleString(), 20, signatureY + 10);

        this.addFooter(doc, 1, 1);

        const fileName = `Complaint_Report_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);

        return fileName;
    }

    // Generate Fuel Station Report PDF
    generateFuelStationReport(data, recipient = 'Admin') {
        const doc = new jsPDF();

        this.addHeader(doc, 'Fuel Station Report', `${data.period} Report - ${data.startDate} to ${data.endDate}`);

        // Recipient Information
        const recipientInfo = {
            name: recipient === 'Admin' ? 'Administration Office' :
                recipient === 'Transport Office' ? 'Transport Office' :
                    'Administration & Transport Offices',
            department: recipient === 'Admin' ? 'University Administration' :
                recipient === 'Transport Office' ? 'Transport Management Department' :
                    'University Administration & Transport Management'
        };
        this.addRecipient(doc, recipientInfo, 50);

        // Report Type Badge
        doc.setFillColor(...this.primaryColor);
        doc.roundedRect(20, 82, 60, 10, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(data.period.toUpperCase() + ' REPORT', 50, 88.5, { align: 'center' });

        let currentY = 100;

        // Summary Statistics Section
        if (data.includeSummary) {
            doc.setTextColor(...this.darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('📊 Summary Statistics', 20, currentY);

            const summaryData = [
                ['Total Fuel Dispensed', `${data.totalFuel} Liters`],
                ['Diesel Dispensed', `${data.dieselDispensed} Liters`],
                ['Petrol Dispensed', `${data.petrolDispensed} Liters`],
                ['Total Transactions', data.totalTransactions.toString()],
                ['Completed Transactions', data.completedTransactions.toString()],
                ['Pending Authorizations', data.pendingAuthorizations.toString()]
            ];

            doc.autoTable({
                startY: currentY + 5,
                body: summaryData,
                theme: 'striped',
                headStyles: {
                    fillColor: this.primaryColor,
                    textColor: [255, 255, 255],
                    fontStyle: 'bold'
                },
                styles: {
                    fontSize: 10,
                    cellPadding: 5
                },
                columnStyles: {
                    0: { fontStyle: 'bold', cellWidth: 80 },
                    1: { cellWidth: 90 }
                },
                margin: { left: 20, right: 20 }
            });

            currentY = doc.lastAutoTable.finalY + 15;
        }

        // Inventory Status Section
        if (data.includeInventory) {
            doc.setTextColor(...this.darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('📦 Current Inventory Status', 20, currentY);

            const inventoryData = [
                ['Diesel Available', `${data.dieselAvailable} Liters`],
                ['Petrol Available', `${data.petrolAvailable} Liters`],
                ['Total Fuel in Stock', `${data.dieselAvailable + data.petrolAvailable} Liters`]
            ];

            doc.autoTable({
                startY: currentY + 5,
                body: inventoryData,
                theme: 'striped',
                styles: {
                    fontSize: 10,
                    cellPadding: 5
                },
                columnStyles: {
                    0: { fontStyle: 'bold', cellWidth: 80 },
                    1: { cellWidth: 90 }
                },
                margin: { left: 20, right: 20 }
            });

            currentY = doc.lastAutoTable.finalY + 15;
        }

        // Transaction Details Section
        if (data.includeTransactions) {
            doc.setTextColor(...this.darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('💳 Transaction Summary', 20, currentY);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...this.textColor);
            doc.text(`This ${data.period.toLowerCase()} period includes ${data.totalTransactions} total transactions,`, 20, currentY + 7);
            doc.text(`with ${data.completedTransactions} successfully completed and ${data.pendingAuthorizations} pending authorization.`, 20, currentY + 14);

            currentY += 25;
        }

        // Report Metadata
        doc.setFillColor(...this.lightGray);
        doc.roundedRect(20, currentY, 170, 35, 3, 3, 'F');

        doc.setTextColor(...this.darkColor);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('Report Information', 25, currentY + 8);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...this.textColor);
        doc.text(`Generated By: ${data.generatedBy}`, 25, currentY + 15);
        doc.text(`Report Date: ${data.date}`, 25, currentY + 21);
        doc.text(`Recipient: ${recipient}`, 25, currentY + 27);

        // Signature Section
        const pageHeight = doc.internal.pageSize.getHeight();
        const signatureY = pageHeight - 60;

        doc.setDrawColor(...this.primaryColor);
        doc.line(20, signatureY, 90, signatureY);
        doc.line(120, signatureY, 190, signatureY);

        doc.setTextColor(...this.textColor);
        doc.setFontSize(9);
        doc.text('Fuel Station Officer', 20, signatureY + 5);
        doc.text('Authorized Signature', 120, signatureY + 5);

        doc.setFontSize(8);
        doc.text(new Date().toLocaleString(), 20, signatureY + 10);

        this.addFooter(doc, 1, 1);

        // Save PDF
        const fileName = `Fuel_Station_Report_${data.period}_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);

        return fileName;
    }

    // Generate Trip Report PDF
    generateTripReport(data, recipient = 'Admin') {
        const doc = new jsPDF();

        this.addHeader(doc, 'Trip Report', 'Trip Summary & Details');

        const recipientInfo = {
            name: recipient === 'Admin' ? 'Administration Office' : 'Transport Office',
            department: recipient === 'Admin' ? 'University Administration' : 'Transport Management Department'
        };
        this.addRecipient(doc, recipientInfo, 50);

        doc.setTextColor(...this.darkColor);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Trip Information', 20, 90);

        const tableData = [
            ['Trip ID', data.tripId || 'N/A'],
            ['Date', data.date || new Date().toLocaleDateString()],
            ['Driver Name', data.driverName || 'John Doe'],
            ['Vehicle ID', data.vehicleId || 'VEH-001'],
            ['Pickup Location', data.pickupLocation || 'N/A'],
            ['Destination', data.destination || 'N/A'],
            ['Start Time', data.startTime || 'N/A'],
            ['End Time', data.endTime || 'N/A'],
            ['Distance', `${data.distance || 'N/A'} km`],
            ['Fuel Used', `${data.fuelUsed || 'N/A'} L`],
            ['Status', data.status || 'Completed']
        ];

        doc.autoTable({
            startY: 95,
            body: tableData,
            theme: 'striped',
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 60 },
                1: { cellWidth: 110 }
            },
            margin: { left: 20, right: 20 }
        });

        if (data.notes) {
            const notesY = doc.lastAutoTable.finalY + 15;
            doc.setTextColor(...this.darkColor);
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Trip Notes:', 20, notesY);

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(...this.textColor);
            const splitNotes = doc.splitTextToSize(data.notes, 170);
            doc.text(splitNotes, 20, notesY + 7);
        }

        const pageHeight = doc.internal.pageSize.getHeight();
        const signatureY = pageHeight - 60;

        doc.setDrawColor(...this.primaryColor);
        doc.line(20, signatureY, 90, signatureY);
        doc.setTextColor(...this.textColor);
        doc.setFontSize(9);
        doc.text('Driver Signature', 20, signatureY + 5);
        doc.setFontSize(8);
        doc.text(new Date().toLocaleString(), 20, signatureY + 10);

        this.addFooter(doc, 1, 1);

        const fileName = `Trip_Report_${data.tripId || 'Unknown'}_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);

        return fileName;
    }
}

export default new PDFGenerator();
